version: "3"
services:

  scrapy:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/opt
    depends_on:
      - postgres

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cicero
      - POSTGRES_USER=cicero
      - POSTGRES_PASSWORD=cicero
    ports:
      - 5432:5432
